# Generated by Django 4.2.1 on 2023-06-17 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ezeladoria', '0002_alter_evento_endrereco'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evento',
            name='Empresa',
        ),
    ]
