# Generated by Django 4.2.1 on 2023-06-20 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ezeladoria', '0003_remove_evento_empresa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='Foto',
            field=models.ImageField(blank=True, null=True, upload_to='medias/'),
        ),
    ]
