name: ezeladoria CI
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ububtu-latest
    steps:
      - name: Checkout do Repositório
        uses: actions/checkout@v1
      - name: Deploy para meu servidor
        uses: easingthemes/ssh-deploy@main
        env: 
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          ARGS: "-rlgoDzvc -i --delete"
          SOURCE: "src/"
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          TARGET: ${{ secrets.REMOTE_TARGET }}

